### ISSUE TITLE
Check for empty/null values

### ISSUE THREAD

**Issue by JayPalm** [samuelcolvin/buildpg#43]
How can I check for null or empty values in a query?

I have tried to write my query in the following ways without any success:

- `V(col_name) is None`
- `V(col_name) == Empty()`
- `V(col_name) is Empty()`

**Comment by samuelcolvin** [comment]
Well `is` can't work since that performs an identity check

`Empty` is not for checking if a value is an empty string, it's to create an empty part of a query.

There are examples of null checks elsewhere, and to check is a string is empty, to an equality check an empty string.

**Comment by JayPalm** [comment]
Gotcha, thanks for the response. I was pretty much just trying things that seemed like they might work because I haven't been able to find any examples of checking for `null` in this repo, but maybe I'm using the wrong keywords.

**Comment by JayPalm** [comment]
For any future viewers struggling with a similar issue, this can be accomplished like this:
`SqlBlock(logic.RawDangerous("nullable_column_name is NULL"))`

**Comment by samuelcolvin** [comment]
Much better to use `V('nullable_column_name').is_(V('null'))`.
